name: Azure Bicep Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep Template to Subscription
      run: |
        az deployment sub create \
          --name "enterprise-setup-deployment-${{ github.run_number }}" \
          --location australiaeast \
          --template-file ./main.bicep \
          --parameters location=australiaeast \
          --rollback-on-error
